[project]
name = "spotify"
version = "0.1"
long_description="A comprehensive Python project aimed at providing solutions for data analysis and visualization."
long_description_content_type='text/markdown'
